### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by yebyen** [teamhephy/postgres#1]
This (rootfs/Dockerfile) doesn't build anymore, as the version of Postgres that it references is too old

![screen shot 2018-04-04 at 1 45 33 pm](https://user-images.githubusercontent.com/1025518/38324484-7aef7fea-380e-11e8-800c-43053f93c697.png)

Should be easy to fix, assuming we can upgrade to (9.6?) without breaking anything.

My experience with a Rails 4 app says we should wait to upgrade to PG 10, but if 9.4 is not supported anymore, first Hephy release should definitely ship with something newer.

This is a release blocker for 2.19

**Comment by Cryptophobia** [comment]
This was fixed with PR #2
