### ISSUE TITLE
v2.7.0 might break backups

### ISSUE THREAD

**Issue by kingdonb** [teamhephy/postgres#8]
Before the new workflow release is cut, I just wanted to confirm that someone has tested Postgres and confirmed that backups work with the new postgres:11 image backing this new release.

Environments to test:

- [ ] AWS
- [ ] Azure
- [ ] Google Cloud

Please report which builds you've tested and I will update the list in this issue (or you can)

**Comment by kingdonb** [comment]
I had issues but I was testing against the new S3_ENDPOINT config that hasn't been merged yet, speaking to Digital Ocean Spaces S3 API.

It seems likely that S3's region certificate authorities signing certs are bundled in the boto2 package.  Then, if that's true, there might be no issues with AWS when the new base image does not include `ca-certificates`, but there could be problems with the other two.  I don't know enough about how the storage works across clouds to say for sure without testing.

Let's be sure before we publish v2.20 and unleash the hordes on it, is all!  Thanks

**Comment by Cryptophobia** [comment]
Not sure how to best test this for all platform. I have only tested in AWS and have not tested the backup process.


> that's true, there might be no issues with AWS when the new base image does not include `ca-certificates`

Are you sure this is the case @kingdonb ? I checked the Docker image build logs from yesterday of the new postgres image and I see that the `ca-certificates` package is being installed while the image was made.

**Comment by Cryptophobia** [comment]
From the logs of the docker image build:

```
The following NEW packages will be installed:
  binutils ca-certificates cpp cpp-6 gcc gcc-6 git git-man gosu libasan3
  libatomic1 libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libcurl3-gnutls
  liberror-perl libexpat1-dev libffi-dev libgcc-6-dev libgdbm3 libgomp1
  libidn2-0 libisl15 libitm1 liblsan0 libmpc3 libmpfr4 libmpx2 libnghttp2-14
  libperl5.24 libpq-dev libpsl5 libpython3-dev libpython3.5 libpython3.5-dev
  libquadmath0 librtmp1 libssh2-1 libssl-dev libtsan0 libubsan0 linux-libc-dev
  lzop perl perl-modules-5.24 pv python-pip-whl python3-dev python3-pip
  python3-pkg-resources python3-setuptools python3-wheel python3.5-dev
```

This is in Step #4 of the Dockerfile.

**Comment by kingdonb** [comment]
OK, that is great news, it was missing when I tested it.

Looks like someone has fixed it already.  I'll close this issue, but it would be good to test all three environments.  That was the missing part, as whatever commit I was building from was missing `ca-certificates` and adding it solved this for me.
